# Generated by Django 3.1.7 on 2021-03-29 12:38

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
