# Generated by Django 3.2.6 on 2021-12-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20210329_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('i', 'In stock'), ('o', 'On Loan')], default='i', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(related_name='book_tags', to='books.Tag'),
        ),
    ]
